# -*- coding: utf-8 -*-
"""C114-Linear-Regression-1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qAeoERCiuWMnbkYKAg42sOflDpDj35Cp
"""

import pandas as pd
import plotly.express as px

from google.colab import files
df = files.upload()

df = pd.read_csv('data.csv')

height = df['Height'].tolist()
weight = df['Weight'].tolist()

fig = px.scatter(x = height, y = weight)
fig.show()

m = 0.95
c = -94
y = []

for i in height:
    y1 = m * i + c
    y.append(y1)

fig = px.scatter(x = height, y = weight)
fig.update_layout(shapes = [dict(type = 'line', y0 = min(y), y1 = max(y), x0 = min(height), x1 = max(height))])
fig.show()

x = 250
y = m * x + c

print("Weight of someone with height", {x}, "is",  {y})

import numpy as np

height1 = np.array(height)
weight1 = np.array(weight)

n,c = np.polyfit(height1, weight1, 1)
y2value = []

for a in height1:
    y2 = m * a + c
    y2value.append(y2)

fig1 = px.scatter(x = height1, y = weight1)
fig1.update_layout(shapes = [dict(type = 'line', y0 = min(y2value), y1 = max(y2value), x0 = min(height1), x1 = max(height1))])
fig1.show()

x = 250
y = m * x + c

print("Weight of someone with height", {x}, "is",  {y})