# -*- coding: utf-8 -*-
"""C114-Linear-Regression-2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H46dSPH3r06Kd5BudEqsnSToRYikcf7O
"""

import pandas as pd
import plotly.express as px

from google.colab import files
df = files.upload()

df = pd.read_csv('main.csv')

greScore = df['GRE Score'].tolist()
ChanceOfAdmit = df['Chance of Admit '].tolist()

fig = px.scatter(x = greScore, y = ChanceOfAdmit)
fig.show()

m = 0.01
c = -2.5
y = []

for i in greScore:
    y1 = m * i + c
    y.append(y1)

fig1 = px.scatter(x = greScore, y = ChanceOfAdmit)
fig1.update_layout(shapes = [dict(type = 'line', y0 = min(y), y1 = max(y), x0 = min(greScore), x1 = max(greScore))])
fig1.show()

x = 600
y = m * x + c

print("Chances of Admission", {x}, "is", {y})

import numpy as np

greScore1 = np.array(greScore)
ChanceOfAdmit1 = np.array(ChanceOfAdmit)

m,c = np.polyfit(greScore1, ChanceOfAdmit1, 1)
y2value = []

for a in greScore1:
    y2 = m * a + c
    y2value.append(y2)


fig2 = px.scatter(x = greScore1, y = ChanceOfAdmit1)
fig2.update_layout(shapes = [dict(type = 'line', y0 = min(y2value), y1 = max(y2value), x0 = min(greScore1), x1 = max(greScore1))])
fig2.show()

x = 600
y = m * x + c

print("Chance Of Admission of someone with Gre Score", {x}, "is",  {y})